In [ ]:
from google.colab import drive
drive._mount('/content/drive')
%cd '/content/drive/MyDrive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data'

Mounted at /content/drive
/content/drive/MyDrive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data


In [ ]:
import pandas as pd
!ls

Kaggle	masked_labels.csv  sample_submission.csv  test	train  train_labels.csv


In [ ]:
df = pd.read_csv('sample_submission.csv')
df

id  target
0      000bf832cae9ff1     0.5
1      000c74cc71a1140     0.5
2      000f5f9851161d3     0.5
3      000f7499e95aba6     0.5
4      00133ce6ec257f9     0.5
...                ...     ...
39990  fff701540fb8aad     0.5
39991  fff9d92a46ea99a     0.5
39992  fffa40260ffe43d     0.5
39993  fffbc626c9d269f     0.5
39994  fffd28bc31bd500     0.5

[39995 rows x 2 columns]

In [ ]:
df = pd.read_csv('train_labels.csv')
df

id  target
0      0000799a2b2c42d       0
1      00042890562ff68       0
2      0005364cdcb8e5b       0
3      0007a5a46901c56       0
4      0009283e145448e       0
...                ...     ...
59995  fff8217fe05aba3       0
59996  fffa939e610ed70       0
59997  fffbb1c9c3d6c31       1
59998  fffc9a763d23647       0
59999  ffff0a799efa529       0

[60000 rows x 2 columns]

In [ ]:
%cd train
!ls

/content/drive/My Drive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data/train
0  1  2  3  4  5  6  7	8  9  a  b  c  d  e  f


In [ ]:
%cd 0
!ls

/content/drive/My Drive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data/train/0
0000799a2b2c42d.npy  0531a1329912a5c.npy  0a6da018dd706bb.npy
00042890562ff68.npy  0531b98e251b14f.npy  0a6e627c5b2d294.npy
0005364cdcb8e5b.npy  053260b6bfd2ba8.npy  0a6f5d4b0cafe4f.npy
0007a5a46901c56.npy  053325825417251.npy  0a71dd3fea19a73.npy
0009283e145448e.npy  0534c38cafb30ad.npy  0a727bb4f8b0b4a.npy
00096524e6670d6.npy  053580460e46209.npy  0a729e5903c8a61.npy
000cd479c2106d4.npy  0537da08863f61a.npy  0a73c69e4a0d143.npy
000e869ed875e40.npy  053c3fda478b51f.npy  0a74f0c8deabf30.npy
00104dc954c2d30.npy  053e9b5f29fa5df.npy  0a755ada4b97267.npy
0010ad3ece01536.npy  053f472f9e65709.npy  0a7617fcc80b23a.npy
00118f68d95f846.npy  053f4c110891fb0.npy  0a76709803627d4.npy
0012dcc6bd1691a.npy  0540be04f5040e9.npy  0a78252581f23d4.npy
0012ef703e41ef0.npy  054237e9ed6d6ee.npy  0a79315faa95da2.npy
00139e3001fac17.npy  05449f27e743fe3.npy  0a7a83bd5483d7a.npy
0014d4e495190df.npy  0544f355638279b.npy  0a

In [ ]:
import numpy as np
ndarray = np.load('0000799a2b2c42d.npy')
ndarray.shape

(6, 273, 256)

In [ ]:
ndarray

array([[[ 3.021  ,  1.593  ,  3.088  , ...,  0.3567 ,  1.493  ,
          1.297  ],
        [ 3.375  ,  2.639  ,  2.168  , ...,  1.01   ,  1.828  ,
          1.314  ],
        [ 2.793  ,  2.81   ,  2.59   , ..., -0.0801 ,  1.13   ,
          0.1048 ],
        ...,
        [ 4.105  ,  4.02   ,  4.465  , ...,  1.664  ,  1.456  ,
          2.719  ],
        [ 4.086  ,  3.742  ,  2.238  , ..., -0.0377 ,  1.281  ,
          1.202  ],
        [ 2.621  ,  2.293  ,  2.973  , ...,  0.2932 ,  1.279  ,
          1.038  ]],

       [[ 2.734  ,  2.338  ,  2.352  , ..., -0.813  ,  0.9224 ,
          0.8843 ],
        [ 2.96   ,  2.648  ,  2.326  , ...,  1.177  ,  1.365  ,
          1.06   ],
        [ 3.02   ,  1.802  ,  1.605  , ...,  0.4224 ,  1.039  ,
          1.094  ],
        ...,
        [ 5.316  ,  5.973  ,  4.754  , ...,  1.593  ,  0.2842 ,
          1.092  ],
        [ 4.434  ,  5.09   ,  3.537  , ...,  1.162  ,  1.54   ,
          1.751  ],
        [ 4.418  ,  2.957  ,  2.541  , ...,  1.4

In [ ]:
print(ndarray)

[[[ 3.021    1.593    3.088   ...  0.3567   1.493    1.297  ]
  [ 3.375    2.639    2.168   ...  1.01     1.828    1.314  ]
  [ 2.793    2.81     2.59    ... -0.0801   1.13     0.1048 ]
  ...
  [ 4.105    4.02     4.465   ...  1.664    1.456    2.719  ]
  [ 4.086    3.742    2.238   ... -0.0377   1.281    1.202  ]
  [ 2.621    2.293    2.973   ...  0.2932   1.279    1.038  ]]

 [[ 2.734    2.338    2.352   ... -0.813    0.9224   0.8843 ]
  [ 2.96     2.648    2.326   ...  1.177    1.365    1.06   ]
  [ 3.02     1.802    1.605   ...  0.4224   1.039    1.094  ]
  ...
  [ 5.316    5.973    4.754   ...  1.593    0.2842   1.092  ]
  [ 4.434    5.09     3.537   ...  1.162    1.54     1.751  ]
  [ 4.418    2.957    2.541   ...  1.468    1.748    1.798  ]]

 [[ 1.502    1.389    1.914   ...  0.5684   0.5337   0.4944 ]
  [ 2.885    0.901    0.815   ...  0.7153   0.4077   1.565  ]
  [ 2.756    2.615    1.866   ...  0.5034   1.063    1.537  ]
  ...
  [ 3.082    2.355    2.252   ... -0.8403  -0.94

In [ ]:
new_arr = ndarray.reshape((1638, 256))
new_arr.shape

(1638, 256)

In [ ]:
a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)
a_3d.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [ ]:
a_2d = a_3d.reshape((6, 4))
print(a_2d)
a_2d.shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


(6, 4)

In [ ]:
df = pd.DataFrame(new_arr)
df

0         1         2    ...       253       254       255
0     3.021484  1.592773  3.087891  ...  0.356689  1.493164  1.296875
1     3.375000  2.638672  2.167969  ...  1.009766  1.828125  1.314453
2     2.792969  2.810547  2.589844  ... -0.080078  1.129883  0.104797
3     1.973633  2.148438  2.396484  ...  0.338623 -0.674805  1.691406
4     3.855469  4.480469  3.261719  ...  1.020508  0.490723  1.837891
...        ...       ...       ...  ...       ...       ...       ...
1633  1.980469  2.810547  2.681641  ... -0.168335 -0.176636  0.025223
1634 -0.062500  0.247925 -0.377930  ... -2.037109  0.610840 -0.494141
1635  2.449219  1.025391  1.180664  ... -1.099609 -1.145508 -0.457520
1636  1.284180  0.463379  1.118164  ... -0.846680  1.380859  0.146362
1637  0.950195  1.388672  0.783203  ... -0.355957 -0.750977 -0.303223

[1638 rows x 256 columns]

In [ ]:
print(df[0])

0       3.021484
1       3.375000
2       2.792969
3       1.973633
4       3.855469
          ...   
1633    1.980469
1634   -0.062500
1635    2.449219
1636    1.284180
1637    0.950195
Name: 0, Length: 1638, dtype: float16


In [ ]:
print(df.iloc[0])

0      3.021484
1      1.592773
2      3.087891
3      3.625000
4      1.832031
         ...   
251    0.910645
252    1.022461
253    0.356689
254    1.493164
255    1.296875
Name: 0, Length: 256, dtype: float16


In [ ]:
df.shape

(1638, 256)

In [ ]:
%cd ..

# Count number of files in train and test directories

import os
import glob

num_files = 0
dir_list = os.listdir('.')
for dir in dir_list:
  for filename in glob.glob(f'{dir}/*.npy'):
    num_files += 1

print(f'Number of files in train: {num_files}')
print(f'Expected: 60000')

/content/drive/My Drive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data/train
Number of files in train: 60000
Expected: 60000


In [ ]:
%cd ../test

num_files = 0
dir_list = os.listdir('.')
for dir in dir_list:
  for filename in glob.glob(f'{dir}/*.npy'):
    num_files += 1

print(f'Number of files in test: {num_files}')
print(f'Expected: 39995')

/content/drive/My Drive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data/test
Number of files in test: 39995
Expected: 39995


In [ ]:
print(f'Discrepancy: {num_files - 39995} files')
print('Searching..\n')

for dir in dir_list:
  for filename in glob.glob(f'{dir}/*(1).npy'):
    print(filename)

Discrepancy: 0 files
Searching..



In [ ]:
%rm d/dbfe7d0e3569ae6\ \(1\).npy
%rm d/df8b5a995c6474f\ \(1\).npy
%rm d/d43c889867d4741\ \(1\).npy
%rm d/d5bca76912f7b6d\ \(1\).npy
%rm d/d5e861018bb1ae4\ \(1\).npy
%rm d/d61240b5f619cbf\ \(1\).npy
%rm d/d6be0b691738de1\ \(1\).npy
%rm d/d2e47b4db591e83\ \(1\).npy

In [ ]:
%cd ../train

/content/drive/My Drive/Research/Ongoing/Dynamic Spectra Sequence Modeling/Data/train


In [ ]:
!pip install transformers

     |████████████████████████████████| 3.4 MB 7.6 MB/s 
     |████████████████████████████████| 596 kB 85.1 MB/s 
     |████████████████████████████████| 61 kB 628 kB/s 
     |████████████████████████████████| 895 kB 60.4 MB/s 
     |████████████████████████████████| 3.3 MB 69.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
%ls 0

0000799a2b2c42d.npy  0531a1329912a5c.npy  0a6da018dd706bb.npy
00042890562ff68.npy  0531b98e251b14f.npy  0a6e627c5b2d294.npy
0005364cdcb8e5b.npy  053260b6bfd2ba8.npy  0a6f5d4b0cafe4f.npy
0007a5a46901c56.npy  053325825417251.npy  0a71dd3fea19a73.npy
0009283e145448e.npy  0534c38cafb30ad.npy  0a727bb4f8b0b4a.npy
00096524e6670d6.npy  053580460e46209.npy  0a729e5903c8a61.npy
000cd479c2106d4.npy  0537da08863f61a.npy  0a73c69e4a0d143.npy
000e869ed875e40.npy  053c3fda478b51f.npy  0a74f0c8deabf30.npy
00104dc954c2d30.npy  053e9b5f29fa5df.npy  0a755ada4b97267.npy
0010ad3ece01536.npy  053f472f9e65709.npy  0a7617fcc80b23a.npy
00118f68d95f846.npy  053f4c110891fb0.npy  0a76709803627d4.npy
0012dcc6bd1691a.npy  0540be04f5040e9.npy  0a78252581f23d4.npy
0012ef703e41ef0.npy  054237e9ed6d6ee.npy  0a79315faa95da2.npy
00139e3001fac17.npy  05449f27e743fe3.npy  0a7a83bd5483d7a.npy
0014d4e495190df.npy  0544f355638279b.npy  0a7afd9305f10ce.npy
00154729d2fd371.npy  0545fad3036f2fd.npy  0a7bdcaf2c2f4e5.npy
0015567a

In [ ]:
import torch
from transformers import BertConfig, BertModel

ndarray_1 = np.load('0/0000799a2b2c42d.npy')
new_arr_1 = ndarray_1.reshape((1638, 256))

ndarray_2 = np.load('0/00042890562ff68.npy')
new_arr_2 = ndarray_2.reshape((1638, 256))

new_arr = np.stack((new_arr_1, new_arr_2))
x_np = torch.from_numpy(new_arr)

# Initializing a custom BERT configuration, where the number of attention heads must be a multiple of the hidden size
configuration = BertConfig(hidden_size=256, num_attention_heads=16)

# Initializing a model from the custom BERT configuration
model = BertModel(configuration)

outputs = model.forward(inputs_embeds=x_np)
print(outputs)
#last_hidden_states = outputs.last_hidden_state

RuntimeError: ignored

In [ ]:
class CustomImageDataset(Dataset):
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(annotations_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label